version: '3'
services:
  node:
    image: node:8
    volumes:
      - /opt/recombot:/opt/recombot
    working_dir: /opt/recombot
    command: npm install && npm run compile && npm start
web:
  environment:
    - TOKEN=${token}